name: BigQuery

on:
  push:
    branches:
      - master
    paths:
      - bigquery/**

jobs:
  create-bucket:
    name: Deploy Cloud Function
    uses: ./.github/workflows/gcp-terraform-reusable-workflow.yml
    with:
      working_dir: bigquery
    secrets: inherit
