# workflow for GCP workload identity federation
name: Creating GCS Bucket via Terraform

on:
  push:
    branches:
      - master
    paths:
      - cloud-storage/1-create-bucket/**

jobs:
  create-bucket:
    name: Create GCS Bucket
    uses: ./.github/workflows/gcp-terraform-reusable-workflow.yml
    with:
      working_dir: cloud-storage/1-create-bucket
    secrets: inherit
