name: Deploy Cloud Function

on:
  push:
    branches:
      - master
    # paths:
    #   - cloud-function/gen-2/cloud-storage-trigger/**

jobs:
  create-bucket:
    name: Deploy Cloud Function
    uses: ./.github/workflows/gcp-terraform-reusable-workflow.yml
    with:
      working_dir: cloud-function/gen-2/cloud-storage-trigger
    secrets: inherit
