# workflow for GCP workload identity federation
name: Cloud Function

on:
  push:
    branches:
      - master

jobs:
  my-job:
    name: apply
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.SA_EMAIL }}"
          token_format: "access_token"
          access_token_lifetime: "100s"
