name: Re-Usable Workflow for GCP Auth and Terraform

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: ${{ github.event.inputs.working_dir }}

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.SA_EMAIL }}"
          token_format: "access_token"
          create_credentials_file: "true"

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan

      # Builds or changes infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
